--USING ADVANTUREWORKS 2022 DATABASE 


--3. PERFORM THE FOLLOWING WITH HELP OF THE ABOVE DATABASE:
---A. GET ALL THE DETAILS FROM THE PERSON TABLE INCLUDING EMAIL ID, PHONE NUMBER AND PHONE NUMBER TYPE
SELECT P.FIRSTNAME,P.LASTNAME,PE.EMAILADDRESSID,PE.EMAILADDRESS FROM [PERSON].[PERSON] P
JOIN [PERSON].[EMAILADDRESS] PE 
ON P.BUSINESSENTITYID=PE.BUSINESSENTITYID
JOIN [PERSON].[PERSONPHONE] PH 
ON PH.BUSINESSENTITYID=PE.BUSINESSENTITYID
JOIN [PERSON].[PHONENUMBERTYPE] TY 
ON TY.PHONENUMBERTYPEID=PH.PHONENUMBERTYPEID


--B. GET THE DETAILS OF THE SALES HEADER ORDER MADE IN MAY 2011
SELECT * FROM [SALES].[SALESORDERHEADER] 
WHERE YEAR(ORDERDATE)=2011 AND MONTH(ORDERDATE)=5 ORDER BY YEAR(ORDERDATE) ASC


--C. GET THE DETAILS OF THE SALES DETAILS ORDER MADE IN THE MONTH OF MAY 2011
SELECT A.* FROM [SALES].[SALESORDERDETAIL] A
JOIN [SALES].[SALESORDERHEADER] S 
ON S.SALESORDERID=A.SALESORDERID 
WHERE YEAR(ORDERDATE)=2011 AND MONTH(ORDERDATE)=5


--D. GET THE TOTAL SALES MADE IN MAY 2011
SELECT SUM(LINETOTAL) AS [TOTAL SALES] FROM [SALES].[SALESORDERDETAIL] A 
JOIN [SALES].[SALESORDERHEADER] S 
ON S.SALESORDERID=A.SALESORDERID 
WHERE YEAR(ORDERDATE)=2011 AND MONTH(ORDERDATE)=5


--E. GET THE TOTAL SALES MADE IN THE YEAR 2011 BY MONTH ORDER BY INCREASING SALES
SELECT MONTH(S.ORDERDATE) AS [MONTH OF THE 2011],SUM(LINETOTAL) AS [TOTAL SALES] FROM [SALES].[SALESORDERDETAIL] A 
JOIN [SALES].[SALESORDERHEADER] S 
ON S.SALESORDERID=A.SALESORDERID 
WHERE YEAR(ORDERDATE)=2011 GROUP BY MONTH(S.ORDERDATE) ORDER BY [TOTAL SALES]


--F. GET THE TOTAL SALES MADE TO THE CUSTOMER WITH FIRSTNAME='GUSTAVO' AND LASTNAME='ACHONG'
SELECT SUM(ORDERQTY) AS [TOTAL SALES] FROM [SALES].[SALESORDERDETAIL]  AS SA
JOIN [SALES].[SALESORDERHEADER] C ON C.SALESORDERID=SA.SALESORDERID
JOIN [SALES].[SALESORDERHEADER] SH ON SH.CREDITCARDID=C.CREDITCARDID
JOIN [PERSON].[PERSON] P ON P.ROWGUID=SH.ROWGUID
WHERE FIRSTNAME='GUSTAVO' AND LASTNAME='ACHONG'