DROP DATABASE IF EXISTS [ORDER]
GO
CREATE DATABASE [ORDER]
GO
CREATE TABLE ORDERS
(
ORDER_ID INT,
ORDER_DATE DATE,
AMOUNT INT,
CUSTOMER_ID INT
)
GO
--INSERTING VALUES
INSERT INTO ORDERS VALUES
(1,'2023/01/25',56000,1),
(2,'2023/02/23',36223,3),
(3,'2023/03/12',23678,5),
(4,'2023/04/13',26373,7),
(5,'2023/05/14',23672,8)
GO
SELECT * FROM ORDERS
GO
GO--1. Arrange the ‘Orders’ dataset in decreasing order of amount
SELECT *
FROM ORDERS
ORDER BY AMOUNT DESC
--2. Create a table with the name ‘Employee_details1’ consisting of thesecolumns: ‘Emp_id’, ‘Emp_name’, ‘Emp_salary’. Create another table withthe name ‘Employee_details2’ consisting of the same columns as the first table.
CREATE TABLE EMPLOYEE_DETAILS1 (
 EMP_ID INT PRIMARY KEY,
 EMP_NAME VARCHAR(50),
 EMP_SALARY DECIMAL(10, 2)
)
CREATE TABLE EMPLOYEE_DETAILS2 (
 EMP_ID INT PRIMARY KEY,
 EMP_NAME VARCHAR(50),
 EMP_SALARY DECIMAL(10, 2)
)
--3. Apply the UNION operator on these two tables
SELECT EMP_ID, EMP_NAME, EMP_SALARY
FROM EMPLOYEE_DETAILS1
UNION
SELECT EMP_ID, EMP_NAME, EMP_SALARY
FROM EMPLOYEE_DETAILS2
--4. Apply the INTERSECT operator on these two tables
SELECT EMP_ID, EMP_NAME, EMP_SALARY
FROM EMPLOYEE_DETAILS1
INTERSECT
SELECT EMP_ID, EMP_NAME,EMP_SALARY
FROM EMPLOYEE_DETAILS2
--5. Apply the EXCEPT operator on these two tables
SELECT EMP_ID, EMP_NAME, EMP_SALARY
FROM EMPLOYEE_DETAILS1
EXCEPT
SELECT EMP_ID, EMP_NAME, EMP_SALARY
FROM EMPLOYEE_DETAILS